# Generated by Django 5.2.11 on 2026-08-25 15:51

import django.db.models.deletion
import mixins.mixins
import validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('additional', models.CharField(blank=True, max_length=255, null=True, verbose_name='additional')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='categories/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': '01. Categories',
                'db_table': 'store_categories',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_featured', 'status'], name='store_categ_is_feat_1b882f_idx'), models.Index(fields=['created_at'], name='store_categ_created_4d9d73_idx'), models.Index(fields=['updated_at'], name='store_categ_updated_8e674b_idx')],
            },
            bases=(mixins.mixins.StripMixin, models.Model, mixins.mixins.ImageTagMixin),
        ),
    ]
