# Generated by Django 5.2.11 on 2026-08-25 16:02

import django.db.models.deletion
import validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='additional_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='additional'),
        ),
        migrations.AddField(
            model_name='category',
            name='additional_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='additional'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_bn',
            field=models.ImageField(default='defaults/default.jpg', null=True, upload_to='categories/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_en',
            field=models.ImageField(default='defaults/default.jpg', null=True, upload_to='categories/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured_bn',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured_en',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_bn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_bn',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='status_bn',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='category',
            name='status_en',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_bn',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured_en', 'status_en'], name='store_categ_is_feat_9217dd_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured_bn', 'status_bn'], name='store_categ_is_feat_091ea9_idx'),
        ),
    ]
