# Generated by Django 5.2.11 on 2026-08-25 07:45

import django.db.models.deletion
import mixins.mixins
import validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('about_text', models.TextField(blank=True, help_text='Short description about the company', null=True, verbose_name='about text')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('copyright_text', models.CharField(default='All rights reserved', help_text='Custom copyright notice line', max_length=255, verbose_name='copyright text')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': '03. Footer',
                'db_table': 'settings_footer',
            },
            bases=(mixins.mixins.StripMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(help_text='Site Logo', max_length=150, unique=True, verbose_name='title')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='logo/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': '02. Logo',
                'db_table': 'settings_logo',
            },
            bases=(mixins.mixins.StripMixin, models.Model, mixins.mixins.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(help_text='e.g. Quick Links, Legal, Policies', max_length=100, verbose_name='title')),
                ('url', models.CharField(help_text='Target URL or path (e.g. /about-us/ or https://example.com)', max_length=500, verbose_name='url')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='setting.footer')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': '04. Links',
                'db_table': 'settings_link',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='settings_li_status_1561c8_idx'), models.Index(fields=['created_at'], name='settings_li_created_6e4c65_idx'), models.Index(fields=['updated_at'], name='settings_li_updated_96cfbb_idx')],
            },
            bases=(mixins.mixins.StripMixin, models.Model),
        ),
    ]
