# Generated by Django 5.2.11 on 2026-08-25 07:55

import mixins.mixins
import validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(help_text='Site Logo', max_length=150, unique=True, verbose_name='title')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='logo/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': '02. Logo',
                'db_table': 'settings_logo',
            },
            bases=(mixins.mixins.StripMixin, models.Model, mixins.mixins.ImageTagMixin),
        ),
    ]
